///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestExecDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestExecDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c37d2f64-5c2b-49e6-a6ad-2dcd49b71c81")]
    public partial class TestExecDemoRepository : RepoGenBaseFolder
    {
        static TestExecDemoRepository instance = new TestExecDemoRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestExecDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("c37d2f64-5c2b-49e6-a6ad-2dcd49b71c81")]
        public static TestExecDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestExecDemoRepository() 
            : base("TestExecDemoRepository", "/", null, 0, false, "c37d2f64-5c2b-49e6-a6ad-2dcd49b71c81", ".\\RepositoryImages\\TestExecDemoRepositoryc37d2f64.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c37d2f64-5c2b-49e6-a6ad-2dcd49b71c81")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestExecDemoRepositoryFolders
    {
    }
#pragma warning restore 0436
}
